### ISSUE TITLE
minor changes to snippet code

### ISSUE THREAD

**Issue by erelsgl** [equalshares/equalshares.net#3]
https://github.com/equalshares/equalshares.net/blob/95740a8879137c6a055ba2002a04a47ad00f8a01/src/components/CodeSnippet/pythonSnippet.js#L63

I suggest to rename "N" to "agents" and "C" to "candidates" and "B" to "budget", to improve readability of the snippets. This may help people who want to customize the code snippet.

Also, adding doctest to the generated functions can be helpful.

**Comment by DominikPeters** [comment]
Thanks, done. I chose `voters` and `projects` and `total_budget`.

Can you say more about what kind of doctest you'd like to see?

**Comment by erelsgl** [comment]
> Can you say more about what kind of doctest you'd like to see?

Just a single line of code that shows how the function should be called, for example:

    >>> equal_shares(["A", "B", "C", "D"], [1, 2, 3, 4], {1:99, 2:100, 3:99, 4:100}, {1:["A","B"], 2:["A","B"], 3:["C","D"], 4:["C","D"]}, 200)
    [1, 3]

**Comment by DominikPeters** [comment]
working on this
