### ISSUE TITLE
Exception fails when project ids are numeric

### ISSUE THREAD

**Issue by erelsgl** [equalshares/equalshares.net#4]
https://github.com/equalshares/equalshares.net/blob/95740a8879137c6a055ba2002a04a47ad00f8a01/src/components/CodeSnippet/pythonSnippet.js#L321

This line failes when the projects are represented by numbers, as it is not allowed to add numbers to strings. Solution: convert the project names to strings, or use format-string such as `f"Tie-breaking failed: tie between projects {best} "`

**Comment by DominikPeters** [comment]
Thanks!
